# Generated by Django 5.2.4 on 2025-08-25 13:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='templates.domain'),
        ),
        migrations.AlterField(
            model_name='control',
            name='control_code',
            field=models.CharField(help_text="Control code like 'AC-001'", max_length=20, validators=[django.core.validators.RegexValidator(message='Control code must be like AC-001, CM-001', regex='^[A-Z]{2,4}-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='control',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='templates.subcategory'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='templates.framework'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='templates.category'),
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.UniqueConstraint(fields=('subcategory', 'control_code'), name='unique_control_code_per_subcategory'),
        ),
    ]
