# Generated by Django 5.2.4 on 2025-07-31 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='effective_date',
            field=models.DateField(default=datetime.date.today, help_text='When this framework version becomes effective'),
        ),
    ]
