# Generated by Django 5.2.4 on 2025-08-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_alter_category_domain_alter_control_control_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_code_per_domain',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_domain',
        ),
        migrations.RemoveConstraint(
            model_name='control',
            name='unique_control_code_per_subcategory',
        ),
        migrations.RemoveConstraint(
            model_name='domain',
            name='unique_domain_code_per_framework',
        ),
        migrations.RemoveConstraint(
            model_name='domain',
            name='unique_domain_name_per_framework',
        ),
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='unique_subcategory_code_per_category',
        ),
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='unique_subcategory_name_per_category',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('domain__isnull', False)), fields=('domain', 'code'), name='unique_category_code_per_domain'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('domain__isnull', False)), fields=('domain', 'name'), name='unique_category_name_per_domain'),
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.UniqueConstraint(condition=models.Q(('subcategory__isnull', False)), fields=('subcategory', 'control_code'), name='unique_control_code_per_subcategory'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('framework__isnull', False)), fields=('framework', 'code'), name='unique_domain_code_per_framework'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('framework__isnull', False)), fields=('framework', 'name'), name='unique_domain_name_per_framework'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'code'), name='unique_subcategory_code_per_category'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'name'), name='unique_subcategory_name_per_category'),
        ),
    ]
