# Generated by Django 5.2.4 on 2025-08-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_remove_category_unique_category_code_per_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='name',
            field=models.CharField(help_text="Short name like 'SOX', 'ISO27001'", max_length=50),
        ),
    ]
