# Generated by Django 5.2.4 on 2025-07-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_alter_framework_effective_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('domain', 'code'), name='unique_category_code_per_domain'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('domain', 'name'), name='unique_category_name_per_domain'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(fields=('framework', 'code'), name='unique_domain_code_per_framework'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(fields=('framework', 'name'), name='unique_domain_name_per_framework'),
        ),
        migrations.AddConstraint(
            model_name='framework',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_framework_name_version'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='unique_subcategory_code_per_category'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_subcategory_name_per_category'),
        ),
    ]
