# Generated by Django 5.2.4 on 2025-08-26 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_compliance', '0002_tenantuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycontrol',
            options={'ordering': ['subcategory', 'sort_order', 'control_code']},
        ),
        migrations.AlterUniqueTogether(
            name='companycontrol',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='CompanyDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_domain_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=1)),
                ('is_customized', models.BooleanField(default=False)),
                ('custom_description', models.TextField(blank=True)),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='company_compliance.companyframework')),
            ],
            options={
                'db_table': 'company_domains',
                'ordering': ['framework', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_category_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=1)),
                ('is_customized', models.BooleanField(default=False)),
                ('custom_description', models.TextField(blank=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='company_compliance.companydomain')),
            ],
            options={
                'db_table': 'company_categories',
                'ordering': ['domain', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_subcategory_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=1)),
                ('is_customized', models.BooleanField(default=False)),
                ('custom_description', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='company_compliance.companycategory')),
            ],
            options={
                'db_table': 'company_subcategories',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='company_compliance.companysubcategory'),
        ),
        migrations.AddConstraint(
            model_name='companycontrol',
            constraint=models.UniqueConstraint(condition=models.Q(('subcategory__isnull', False)), fields=('subcategory', 'control_code'), name='unique_company_control_code_per_subcategory'),
        ),
        migrations.RemoveField(
            model_name='companycontrol',
            name='framework',
        ),
        migrations.AddConstraint(
            model_name='companydomain',
            constraint=models.UniqueConstraint(condition=models.Q(('framework__isnull', False)), fields=('framework', 'code'), name='unique_company_domain_code_per_framework'),
        ),
        migrations.AddConstraint(
            model_name='companycategory',
            constraint=models.UniqueConstraint(condition=models.Q(('domain__isnull', False)), fields=('domain', 'code'), name='unique_company_category_code_per_domain'),
        ),
        migrations.AddConstraint(
            model_name='companysubcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'code'), name='unique_company_subcategory_code_per_category'),
        ),
    ]
